- name: Variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com   #play level declaration   all the tasks access the play level variables
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}           # task variables
      vars:
        URL: tasks.google.com
    - name: print task variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.google.com #local variables have high priority

