- name: Variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: print task variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}

        vars:
          URL: tasks.google.com

